version: '3'
services:
  web:
    build: .
  postgres:
    image: "postgres"
    ports:
     - "5432:5432"
    environment: 
      POSTGRES_PASSWORD: ""
  nginx:
    image: "nginx"
    ports:
     - "8080:8080"
     - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
